In [3]:
from itertools import groupby

import pandas as pd

df = pd.read_csv("New.csv")

In [15]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [16]:
df.isnull().sum()

OrderID         0
CustomerName    0
Product         0
Category        0
Quantity        0
Price           3
OrderDate       0
Shipped         0
Country         0
dtype: int64

In [9]:
df.groupby("Country")['Price'].sum()

Country
Australia      361.99
Canada        2172.45
France        1559.47
Germany       2262.98
U.S.A         1385.00
UK            1595.48
USA          17619.94
germany         83.00
usa           1419.99
Name: Price, dtype: float64

In [10]:
df.groupby("Category")["Price"].mean()

Category
Apparel         49.733830
Electronics    460.201296
Home Goods      28.198500
Media           18.000000
Name: Price, dtype: float64

In [11]:
df[df['Shipped'] == 'No'].groupby('Country')['OrderID'].count()

Country
Canada      8
France      4
Germany     4
U.S.A       1
UK         11
USA        10
germany     1
Name: OrderID, dtype: int64

In [14]:
df.groupby('Country')['OrderID'].count()

Country
Australia     5
Canada       28
France       21
Germany      19
U.S.A         4
UK           29
USA          40
germany       3
usa           3
Name: OrderID, dtype: int64

In [18]:
df['OrderDate'] = pd.to_datetime(df['OrderDate']) #makes data type date time, not string

In [19]:
df['OrderMonth'] = df['OrderDate'].dt.month_name()

In [20]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country,OrderMonth
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA,June
1,1002,Alice Johnson,Keyboard,Electronics,2,75.50,2024-06-01,No,Canada,June
2,1003,Robert Brown,T-Shirt,Apparel,5,25.00,2024-06-02,Yes,UK,June
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,usa,June
4,1005,Michael Wilson,Mouse Pad,Electronics,10,10.00,2024-06-03,Yes,Germany,June

In [22]:
# CODE TO RUN:
df.groupby('Product')['Quantity'].sum().sort_values(ascending=True)

Product
Desk Lamp          1
Dress              1
Coffee Maker       1
Router             1
Smartwatch         2
Keyboard           3
Jacket             4
Speakers           4
Sweater            4
Webcam             4
Pants              5
Running Shoes      5
Toaster            5
Blender            5
Charging Dock      5
Software           5
Storage Bin        6
Hat                6
Gloves             6
External Drive     6
Jeans              7
Laptop             7
Scarf              8
Headphones         9
Monitor           10
Candle Set        10
Mug               11
Picture Frame     12
Book              15
T-Shirt           16
Pillow            17
Mouse Pad         18
Socks             23
USB Cable         32
Name: Quantity, dtype: int64

In [23]:
# CODE TO RUN:
df[(df['Country'] == 'USA') & (df['Category'] == 'Apparel')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country,OrderMonth
11,1012,Maria Hernandez,Socks,Apparel,12,8.5,2024-06-07,Yes,USA,June
34,1035,Logan Walker,Sweater,Apparel,-2,65.0,2024-06-23,No,USA,June
47,1048,Jackson Hall,Jeans,Apparel,1,45.0,2024-07-02,Yes,USA,July
79,1080,Isaac Nelson,T-Shirt,Apparel,1,25.0,2024-08-03,Yes,USA,August
87,1088,Isabella Baker,Sweater,Apparel,1,65.0,2024-08-11,No,USA,August
91,1092,Grace Foster,Gloves,Apparel,1,22.0,2024-08-15,No,USA,August
97,1098,Sofia Perez,Hat,Apparel,1,20.0,2024-08-21,No,USA,August
113,1113,Grace Foster,Socks,Apparel,1,8.5,2024-09-05,Yes,USA,September
126,1126,Logan Walker,Hat,Apparel,1,20.0,2024-09-18,Yes,USA,September

In [24]:
df['OrderWeekday'] = df['OrderDate'].dt.day_name()

In [27]:
df.groupby('OrderWeekday')['Price'].mean().sort_values(ascending=False)

OrderWeekday
Sunday       765.400000
Saturday     250.020000
Wednesday    101.402381
Tuesday       81.303913
Thursday      75.249000
Monday        61.223500
Friday        30.588636
Name: Price, dtype: float64

In [28]:
df[(df['OrderWeekday'] == 'Monday') & (df['Quantity'] == 1)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country,OrderMonth,OrderWeekday
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,usa,June,Monday
24,1025,Andrew Harris,Software,Electronics,1,99.99,2024-06-17,No,USA,June,Monday
25,1026,Victoria Reed,Jacket,Apparel,1,130.00,2024-06-17,Yes,Germany,June,Monday
35,1036,Mason Gray,Router,Electronics,1,79.99,2024-06-24,Yes,Canada,June,Monday
46,1047,Evelyn Rodriguez,Keyboard,Electronics,1,75.50,2024-07-01,Yes,France,July,Monday
53,1054,Michael Wilson,Blender,Home Goods,1,NaN,2024-07-08,No,USA,July,Monday
60,1061,Maria Hernandez,Book,Media,1,18.00,2024-07-15,Yes,USA,July,Monday
74,1075,Victoria Reed,Pants,Apparel,1,55.00,2024-07-29,Yes,Germany,July,Monday
81,1082,William Flores,Running Shoes,Apparel,1,110.00,2024-08-05,No,France,August,Monday
88,1089,Noah Adams,Pillow,Home Goods,1,20.00,2024-08-12,Yes,Canada,August,Monday
95,1096,Victoria Reed,Candle Set,Home Goods,1,28.00,2024-08-19,Yes,Germany,August,Monday
103,1103,William Flores,Pants,Apparel,1,55.00,2024-08-26,Yes,France,August,Monday
110,1110,Noah Adams,Running Shoes,Apparel,1,110.00,2024-09-02,No,UK,September,Monday
117,1117,Victoria Reed,Pillow,Home Goods,1,20.00,2024-09-09,Yes,Germany,September,Monday
124,1124,William Flores,Candle Set,Home Goods,1,28.00,2024-09-16,No,France,September,Monday
131,1131,Noah Adams,Pants,Apparel,1,55.00,2024-09-23,No,Canada,September,Monday
138,1138,Victoria Reed,Running Shoes,Apparel,1,110.00,2024-09-30,No,Germany,September,Monday
145,1145,William Flores,Pillow,Home Goods,1,20.00,2024-10-07,Yes,France,October,Monday

In [31]:
df[['Price', 'Quantity']].describe()

              Price    Quantity
count    149.000000  152.000000
mean     191.008725    1.802632
std     1001.929517    2.058867
min      -10.000000   -2.000000
25%       18.000000    1.000000
50%       39.990000    1.000000
75%       99.990000    2.000000
max    12000.000000   15.000000

In [32]:
# CODE TO RUN:
df['Product'].value_counts().head(5)

Product
Pillow        9
Monitor       9
Book          8
Candle Set    8
Laptop        7
Name: count, dtype: int64

In [33]:
# CODE TO RUN:
df[['Price', 'Quantity']].corr()

            Price  Quantity
Price     1.00000  -0.06697
Quantity -0.06697   1.00000