In [3]:
from sklearn.datasets import load_iris
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split

X,y = load_iris(return_X_y=True)
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=.2)

In [4]:
scalar = StandardScaler()

X_train_scaled = scalar.fit_transform(X_train)
X_test_Scaled = scalar.transform(X_test)

X_train_scaled

array([[ 0.68860729, -0.8372372 ,  0.90852484,  0.97478193],
       [-0.02579797, -0.60194806,  0.79699237,  1.62535941],
       [ 0.68860729, -0.60194806,  1.07582353,  1.36512842],
       [ 2.23648533, -0.60194806,  1.68925206,  1.10489743],
       [ 0.68860729, -0.36665891,  0.35086253,  0.19408895],
       [ 0.68860729,  0.33920851,  0.46239499,  0.45431994],
       [-0.85927076,  1.75094337, -1.15482569, -1.23718151],
       [ 0.21233712, -0.36665891,  0.46239499,  0.45431994],
       [ 2.11741779, -0.13136977,  1.63348583,  1.23501292],
       [-1.69274356,  0.33920851, -1.32212438, -1.23718151],
       [-0.50206814, -0.13136977,  0.46239499,  0.45431994],
       [ 0.33140466, -1.07252634,  1.07582353,  0.32420445],
       [-0.02579797, -0.8372372 ,  0.23933007, -0.19625754],
       [ 2.23648533, -0.13136977,  1.35465468,  1.49524392],
       [-0.38300059, -1.30781548,  0.18356384,  0.19408895],
       [ 1.04580991, -1.30781548,  1.18735599,  0.84466643],
       [ 0.56953974, -1.30781548,  0.68545991,  0.45431994],
       [ 0.68860729,  0.10391937,  1.0200573 ,  0.84466643],
       [ 0.56953974, -0.60194806,  0.79699237,  0.45431994],
       [ 1.76021517, -0.36665891,  1.46618714,  0.84466643],
       [-0.85927076,  1.04507594, -1.26635815, -1.10706602],
       [-1.21647339,  0.8097868 , -1.15482569, -1.23718151],
       [ 0.56953974, -1.77839377,  0.40662876,  0.19408895],
       [-0.74020322,  1.04507594, -1.21059192, -1.23718151],
       [-0.26393305, -0.36665891, -0.03950108,  0.19408895],
       [ 1.64114762, -0.13136977,  1.18735599,  0.58443544],
       [ 1.04580991, -0.13136977,  0.8527586 ,  1.49524392],
       [-0.9783383 ,  1.04507594, -1.15482569, -0.71671953],
       [ 0.80767483, -0.60194806,  0.51816122,  0.45431994],
       [-0.9783383 ,  1.28036508, -1.26635815, -1.23718151],
       [ 0.33140466, -0.36665891,  0.57392745,  0.32420445],
       [ 0.56953974,  0.57449766,  0.57392745,  0.58443544],
       [ 1.283945  ,  0.33920851,  1.13158976,  1.49524392],
       [-0.38300059, -1.54310463,  0.07203138, -0.06614204],
       [ 2.47462042,  1.75094337,  1.52195337,  1.10489743],
       [-0.74020322,  2.45681079, -1.21059192, -1.36729701],
       [ 0.92674237, -0.36665891,  0.51816122,  0.19408895],
       [ 0.33140466, -0.60194806,  0.18356384,  0.19408895],
       [ 0.09326957, -0.13136977,  0.2950963 ,  0.45431994],
       [ 1.40301254,  0.33920851,  0.57392745,  0.32420445],
       [ 0.68860729,  0.33920851,  0.90852484,  1.49524392],
       [-1.09740585,  1.28036508, -1.26635815, -1.36729701],
       [-0.85927076,  1.75094337, -1.21059192, -1.10706602],
       [-0.26393305, -0.60194806,  0.68545991,  1.10489743],
       [-0.9783383 , -2.48426119, -0.09526731, -0.19625754],
       [ 1.283945  ,  0.10391937,  0.79699237,  1.49524392],
       [-0.50206814,  0.8097868 , -1.21059192, -0.97695052],
       [-0.62113568,  1.51565423, -1.21059192, -1.23718151],
       [ 1.87928271, -0.60194806,  1.35465468,  0.97478193],
       [-1.57367602, -1.77839377, -1.32212438, -1.10706602],
       [-0.38300059,  1.04507594, -1.32212438, -1.23718151],
       [-0.26393305, -0.13136977,  0.46239499,  0.45431994],
       [-0.85927076,  1.04507594, -1.26635815, -1.23718151],
       [-1.21647339, -0.13136977, -1.26635815, -1.36729701],
       [-0.85927076,  1.75094337, -0.98752699, -0.97695052],
       [-0.14486551, -0.36665891,  0.2950963 ,  0.19408895],
       [ 0.80767483, -0.13136977,  1.0200573 ,  0.84466643],
       [-1.09740585, -0.13136977, -1.26635815, -1.23718151],
       [ 0.09326957,  0.33920851,  0.62969368,  0.84466643],
       [ 0.33140466, -0.60194806,  0.57392745,  0.06397345],
       [-0.38300059, -1.54310463,  0.01626515, -0.19625754],
       [-1.33554093,  0.33920851, -1.15482569, -1.23718151],
       [-1.33554093,  0.33920851, -1.32212438, -1.23718151],
       [ 0.33140466, -0.13136977,  0.51816122,  0.32420445],
       [-0.14486551, -0.60194806,  0.46239499,  0.19408895],
       [-1.21647339,  0.10391937, -1.15482569, -1.23718151],
       [-0.9783383 ,  0.57449766, -1.26635815, -1.23718151],
       [ 1.64114762,  1.28036508,  1.35465468,  1.75547491],
       [-1.45460847,  0.10391937, -1.21059192, -1.23718151],
       [-0.9783383 ,  0.8097868 , -1.21059192, -1.23718151],
       [ 1.283945  ,  0.10391937,  0.96429107,  1.23501292],
       [-1.69274356, -0.36665891, -1.26635815, -1.23718151],
       [-0.50206814,  1.98623251, -1.09905946, -0.97695052],
       [-0.14486551,  1.75094337, -1.09905946, -1.10706602],
       [ 0.21233712, -2.01368291,  0.18356384, -0.19625754],
       [ 0.68860729, -0.60194806,  1.07582353,  1.23501292],
       [ 1.04580991,  0.10391937,  0.57392745,  0.45431994],
       [ 1.16487745, -0.60194806,  0.62969368,  0.32420445],
       [-1.69274356, -0.13136977, -1.32212438, -1.23718151],
       [-1.21647339, -0.13136977, -1.26635815, -1.10706602],
       [-0.50206814,  0.8097868 , -1.09905946, -1.23718151],
       [-0.9783383 ,  0.33920851, -1.37789061, -1.23718151],
       [ 0.80767483,  0.33920851,  0.79699237,  1.10489743],
       [ 0.56953974, -0.8372372 ,  0.68545991,  0.84466643],
       [-0.26393305, -1.30781548,  0.12779761, -0.06614204],
       [-0.85927076,  0.57449766, -1.09905946, -0.84683502],
       [-0.14486551, -1.30781548,  0.74122614,  1.10489743],
       [ 0.21233712, -0.8372372 ,  0.79699237,  0.58443544],
       [-1.21647339,  0.8097868 , -0.98752699, -1.23718151],
       [-0.38300059, -1.07252634,  0.40662876,  0.06397345],
       [ 0.4504722 , -2.01368291,  0.46239499,  0.45431994],
       [-1.09740585,  0.10391937, -1.21059192, -1.36729701],
       [-0.9783383 , -0.13136977, -1.15482569, -1.23718151],
       [ 2.23648533, -1.07252634,  1.80078452,  1.49524392],
       [-1.09740585,  0.10391937, -1.21059192, -1.23718151],
       [ 0.4504722 ,  0.8097868 ,  0.96429107,  1.49524392],
       [-1.09740585, -1.30781548,  0.46239499,  0.71455094],
       [-1.8118111 , -0.13136977, -1.43365684, -1.36729701],
       [ 0.80767483, -0.13136977,  0.8527586 ,  1.10489743],
       [-0.14486551, -1.07252634, -0.09526731, -0.19625754],
       [ 0.4504722 , -0.60194806,  0.62969368,  0.84466643],
       [-1.45460847,  0.33920851, -1.26635815, -1.23718151],
       [-0.85927076, -1.30781548, -0.37409846, -0.06614204],
       [-0.14486551,  3.16267822, -1.21059192, -0.97695052],
       [ 0.33140466, -0.13136977,  0.68545991,  0.84466643],
       [ 0.80767483, -0.13136977,  1.18735599,  1.36512842],
       [ 0.4504722 , -0.36665891,  0.35086253,  0.19408895],
       [ 0.56953974, -0.36665891,  1.07582353,  0.84466643],
       [-0.02579797,  2.22152165, -1.37789061, -1.23718151],
       [ 1.04580991,  0.57449766,  1.13158976,  1.75547491],
       [-0.50206814,  1.98623251, -1.32212438, -0.97695052],
       [-0.02579797, -0.8372372 ,  0.79699237,  0.97478193],
       [-0.26393305, -0.8372372 ,  0.2950963 ,  0.19408895],
       [ 1.64114762,  0.33920851,  1.29888845,  0.84466643],
       [-0.9783383 ,  1.04507594, -1.32212438, -1.10706602],
       [ 0.56953974,  0.57449766,  1.29888845,  1.75547491],
       [-0.02579797, -1.07252634,  0.18356384,  0.06397345],
       [-0.9783383 ,  0.8097868 , -1.15482569, -0.97695052],
       [ 1.283945  ,  0.10391937,  0.68545991,  0.45431994],
       [-0.85927076,  0.8097868 , -1.21059192, -1.23718151]])

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler =  MinMaxScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_Scaled = scalar.transform(X_test)

X_train-np.mean(X_train, axis=0)
X_min = np.min(X_train, axis = 0)
X_min = np.max(X_train, axis = 0)
(X_train -X_min)/(X_max - X_min)

In [9]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

data = fetch_openml('car', as_frame=True).frame
# have to transform into ordinal numbers

columns_to_encode = ['lug_boot', 'safety']

encoder = OrdinalEncoder(
     categories=[
         ['small', 'med', 'big'],
         ['low', 'med', 'high']
     ]
 )
data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

data

C:\Users\zsche\IdeaProjects\PythonBegginerProjects\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [10]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

In [11]:
data = fetch_openml('adult', as_frame=True).frame

data

C:\Users\zsche\IdeaProjects\PythonBegginerProjects\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [13]:
from sklearn.preprocessing import OneHotEncoder

data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [19]:
import pandas as pd
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_values = encoder.fit_transform(data[['occupation', 'race']])
new_cols = encoder.get_feature_names_out(['occupation', 'race'])

df_encoded = pd.DataFrame(encoded_values, columns=new_cols, index=data.index)
data_final = pd.concat(
    [data.drop(columns =['occupation', 'race']), df_encoded]
)

data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516.0,Bachelors,13.0,Never-married,Not-in-family,Male,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Husband,Male,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Private,215646.0,HS-grad,9.0,Divorced,Not-in-family,Male,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Private,234721.0,11th,7.0,Married-civ-spouse,Husband,Male,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Wife,Female,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0